### ISSUE TITLE
Fails to compile in recent versions

### ISSUE THREAD

**Issue by deingithub** [OscarBarrett/crystal-sha3#7]
Since the merge of crystal-lang/crystal#7581, the library can't compile anymore due to usage of Slice#pointer in https://github.com/OscarBarrett/crystal-sha3/blob/master/src/digest/sha3.cr#L70.

Also, https://github.com/OscarBarrett/crystal-sha3/blob/master/src/digest/sha3.cr#L82 needs to use `//` because the `/` operator now returns floats instead of integers.

**Comment by OscarBarrett** [comment]
Thanks for reporting - I'll do up a fix for those changes.
